name: Automerge staging -> main

on:
  # Triggers the workflow on pull request close events but only for the "staging" branch
  pull_request:
    branches: [ "staging" ]
    types:
      - closed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
 merge-branch:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: everlytic/branch-merge@1.1.2
        with:
          github_token: ${{ github.token }}
          source_ref: 'staging'
          target_branch: 'main'
          commit_message_template: '[Automated] Merged staging into target main'
