name: Automerge staging -> main

on:
  # Triggers the workflow on pull request close events but only for the "staging" branch
  pull_request:
    branches: [ "staging" ]
    types:
      - closed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  merge-staging-to-main:
    if: github.event.pull_request.merged == true
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge staging to main
        run: |
          git fetch --unshallow
          git checkout main
          git pull
          git merge staging -m "[Automated] Merged staging into target main"
          git push
